version: '3.9'

services:
  service:
    container_name: service
    image: clock/service:1.0.0
    build: .
    ports:
      - 3004:3004
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db 
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - CURRENTS_API_KEY=FeMgcQjcdMt46lAB1hT45Krgx4E8R1oyYHENP6zEcxGFuo9_
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}